
CREATE TABLE accounts (
    id                    VARCHAR(64) PRIMARY KEY,
    display_name          VARCHAR(200) NOT NULL,
    masked_account_number VARCHAR(64)  NOT NULL,
    country_code          CHAR(2),
    risk_level            VARCHAR(10)  NOT NULL DEFAULT 'LOW',
    status                VARCHAR(10)  NOT NULL DEFAULT 'ACTIVE',
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE payees (
    id                    VARCHAR(64) PRIMARY KEY,
    display_name          VARCHAR(200) NOT NULL,
    masked_account_number VARCHAR(64),
    country_code          CHAR(2),
    status                VARCHAR(10)  NOT NULL DEFAULT 'ACTIVE',
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE rules (
    id         VARCHAR(64) PRIMARY KEY,
    name       VARCHAR(200) NOT NULL,
    type       VARCHAR(20)  NOT NULL,   -- AMOUNT_THRESHOLD | VELOCITY | NEW_PAYEE | DAILY_LIMIT
    severity   VARCHAR(10)  NOT NULL,   -- LOW | MEDIUM | HIGH
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    config     JSONB        NOT NULL,
    version    INTEGER      NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE rule_history (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id           VARCHAR(64)   NOT NULL REFERENCES rules (id),
    version           INTEGER       NOT NULL,
    action            VARCHAR(20)   NOT NULL,   -- CREATED | UPDATED | ACTIVATED | DEACTIVATED
    previous_snapshot JSONB,
    new_snapshot      JSONB         NOT NULL,
    changed_fields    JSONB         NOT NULL,
    changed_by        VARCHAR(128)  NOT NULL DEFAULT 'SYSTEM',
    changed_at        TIMESTAMPTZ   NOT NULL DEFAULT now(),
    reason            VARCHAR(1000) NOT NULL,
    correlation_id    VARCHAR(128)  NOT NULL,
    UNIQUE (rule_id, version)
);

CREATE TABLE transactions (
    id                       VARCHAR(64) PRIMARY KEY,
    account_id               VARCHAR(64)    NOT NULL REFERENCES accounts (id),
    payee_id                 VARCHAR(64)    NOT NULL REFERENCES payees (id),
    amount                   NUMERIC(19, 4) NOT NULL,
    currency                 CHAR(3)        NOT NULL,
    type                     VARCHAR(10)    NOT NULL,   -- DEBIT | CREDIT | REFUND
    status                   VARCHAR(10)    NOT NULL,   -- PENDING | COMPLETED | FAILED | CANCELLED | REVERSED
    transaction_time         TIMESTAMPTZ    NOT NULL,
    received_at              TIMESTAMPTZ    NOT NULL DEFAULT now(),
    evaluation_mode          VARCHAR(15),               -- REAL_TIME | LATE_ARRIVAL
    evaluated_at             TIMESTAMPTZ,
    description              VARCHAR(500),
    ip_address               VARCHAR(45),
    device_id                VARCHAR(256),
    channel                  VARCHAR(10),               -- WEB | APP | API | BRANCH
    country_code             CHAR(2),
    payment_method           VARCHAR(15),               -- BANK_TRANSFER | CARD | WALLET
    reference_transaction_id VARCHAR(64)    REFERENCES transactions (id),
    payload_hash             CHAR(64)       NOT NULL,
    version                  INTEGER        NOT NULL DEFAULT 0,
    created_at               TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ    NOT NULL DEFAULT now()
);

CREATE INDEX idx_transactions_account_time ON transactions (account_id, status, transaction_time);
CREATE INDEX idx_transactions_account_payee_time ON transactions (account_id, payee_id, status, transaction_time);
CREATE INDEX idx_transactions_status_time ON transactions (status, transaction_time DESC);
CREATE INDEX idx_transactions_payee ON transactions (payee_id, transaction_time DESC);
CREATE INDEX idx_transactions_reference ON transactions (reference_transaction_id);

CREATE TABLE alerts (
    id                           VARCHAR(64) PRIMARY KEY,
    rule_id                      VARCHAR(64)   NOT NULL REFERENCES rules (id),
    rule_version                 INTEGER       NOT NULL,
    account_id                   VARCHAR(64)   NOT NULL REFERENCES accounts (id),
    primary_payee_id             VARCHAR(64)   REFERENCES payees (id),
    first_trigger_transaction_id VARCHAR(64)   NOT NULL REFERENCES transactions (id),
    deduplication_key            VARCHAR(256)  NOT NULL UNIQUE,
    status                       VARCHAR(15)   NOT NULL DEFAULT 'OPEN',
                                 -- OPEN | ACKNOWLEDGED | INVESTIGATING | CLOSED | DISMISSED
    severity                     VARCHAR(10)   NOT NULL,   -- LOW | MEDIUM | HIGH
    reason_text                  VARCHAR(2000) NOT NULL,
    rule_snapshot                JSONB         NOT NULL,
    trigger_context              JSONB         NOT NULL,
    schema_version               INTEGER       NOT NULL DEFAULT 1,
    episode_start                TIMESTAMPTZ   NOT NULL,
    last_triggered_at            TIMESTAMPTZ   NOT NULL,
    transaction_count            INTEGER       NOT NULL DEFAULT 1,
    cumulative_amount            NUMERIC(19, 4),
    resolution_code              VARCHAR(30),
                                 -- LEGITIMATE_ACTIVITY | FALSE_POSITIVE | DUPLICATE_ALERT
                                 -- | RULE_CONFIGURATION_ISSUE | SUSPICIOUS_ACTIVITY | OTHER
    resolution_notes             VARCHAR(2000),
    version                      INTEGER       NOT NULL DEFAULT 1,
    created_at                   TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at                   TIMESTAMPTZ   NOT NULL DEFAULT now(),
    acknowledged_at              TIMESTAMPTZ,
    investigation_started_at     TIMESTAMPTZ,
    closed_at                    TIMESTAMPTZ,
    dismissed_at                 TIMESTAMPTZ
);

CREATE INDEX idx_alerts_queue ON alerts (status, severity, created_at DESC);
CREATE INDEX idx_alerts_episode_lookup ON alerts (rule_id, account_id, status, last_triggered_at DESC);
CREATE INDEX idx_alerts_account ON alerts (account_id, created_at DESC);
CREATE INDEX idx_alerts_payee ON alerts (primary_payee_id, created_at DESC);
CREATE INDEX idx_alerts_rule ON alerts (rule_id, created_at DESC);

CREATE TABLE alert_transactions (
    alert_id       VARCHAR(64) NOT NULL REFERENCES alerts (id),
    transaction_id VARCHAR(64) NOT NULL REFERENCES transactions (id),
    linked_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    link_reason    VARCHAR(20) NOT NULL,   -- FIRST_TRIGGER | WINDOW_CONTEXT | SUBSEQUENT_TRIGGER
    PRIMARY KEY (alert_id, transaction_id)
);

CREATE INDEX idx_alert_transactions_transaction ON alert_transactions (transaction_id);

CREATE TABLE alert_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alert_id        VARCHAR(64)  NOT NULL REFERENCES alerts (id),
    event_type      VARCHAR(30)  NOT NULL,   -- CREATED | TRANSACTION_LINKED | TRIGGER_METRICS_UPDATED
                                             -- | STATUS_CHANGED | RESOLUTION_UPDATED
    from_status     VARCHAR(15),
    to_status       VARCHAR(15),
    note            VARCHAR(2000),
    previous_values JSONB,
    new_values      JSONB,
    changed_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    changed_by      VARCHAR(128) NOT NULL DEFAULT 'SYSTEM',
    source          VARCHAR(10)  NOT NULL DEFAULT 'SYSTEM',   -- SYSTEM | OPERATOR | BATCH
    correlation_id  VARCHAR(128) NOT NULL
);

CREATE INDEX idx_alert_history_timeline ON alert_history (alert_id, changed_at);

CREATE TABLE idempotency_records (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_scope VARCHAR(200) NOT NULL,
    idempotency_key VARCHAR(128) NOT NULL,
    request_hash    CHAR(64)     NOT NULL,
    status          VARCHAR(10)  NOT NULL,   -- PROCESSING | SUCCEEDED | FAILED
    http_status     SMALLINT,
    response_body   JSONB,
    resource_id     VARCHAR(128),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    expires_at      TIMESTAMPTZ  NOT NULL,
    UNIQUE (operation_scope, idempotency_key)
);

CREATE INDEX idx_idempotency_expiry ON idempotency_records (expires_at);

BEGIN;

-- ---------------------------------------------------------------- accounts
INSERT INTO accounts (id, display_name, masked_account_number, country_code, risk_level, status, created_at) VALUES
('ACC-1001', 'Nadia Farouk',        '****4417', 'FR', 'HIGH',   'ACTIVE',   '2024-06-02 09:00:00+00'),
('ACC-1002', 'Global Textiles Ltd', '****8890', 'GB', 'MEDIUM', 'ACTIVE',   '2023-11-14 09:00:00+00'),
('ACC-1003', 'Somchai Prasert',     '****2035', 'TH', 'LOW',    'ACTIVE',   '2025-01-20 09:00:00+00'),
('ACC-1004', 'Rivera Imports SL',   '****7712', 'ES', 'MEDIUM', 'BLOCKED',  '2022-03-08 09:00:00+00'),
('ACC-1005', 'Chen Wei',            '****6604', 'SG', 'LOW',    'ACTIVE',   '2025-09-01 09:00:00+00');

-- ------------------------------------------------------------------ payees
INSERT INTO payees (id, display_name, masked_account_number, country_code, status, created_at) VALUES
('PAY-2001', 'Bright Solar Ltd',     '****3301', 'GB', 'ACTIVE',  '2024-02-01 09:00:00+00'),
('PAY-2002', 'QuickCash Exchange',   '****9982', NULL, 'BLOCKED', '2024-05-11 09:00:00+00'),
('PAY-2003', 'Agence Dupont Immo',   '****1140', 'FR', 'ACTIVE',  '2024-06-03 09:00:00+00'),
('PAY-2004', 'Bangkok Utilities',    '****5567', 'TH', 'ACTIVE',  '2025-01-22 09:00:00+00'),
('PAY-2005', 'Offshore Holdings SA', '****0028', 'KY', 'ACTIVE',  '2026-03-01 09:00:00+00'),
('PAY-2006', 'Shenzhen Fabric Co',   '****4471', 'CN', 'ACTIVE',  '2025-08-19 09:00:00+00'),
('PAY-2007', 'Emma Rivera',          '****6650', 'ES', 'ACTIVE',  '2023-04-04 09:00:00+00'),
('PAY-2008', 'CloudHost Inc',        '****7789', 'US', 'ACTIVE',  '2026-03-13 09:00:00+00');

-- ------------------------------------------------------------------- rules
INSERT INTO rules (id, name, type, severity, active, config, version, created_at, updated_at) VALUES
('RULE-AMT-01', 'Single payment over 10 000',    'AMOUNT_THRESHOLD', 'HIGH',   TRUE,
 '{"schemaVersion": 1, "threshold": 10000, "currency": "EUR"}', 1,
 '2025-06-01 10:00:00+00', '2025-06-01 10:00:00+00'),
('RULE-VEL-01', 'More than 5 payments in 1 hour', 'VELOCITY',        'MEDIUM', TRUE,
 '{"schemaVersion": 1, "maxCount": 5, "windowMinutes": 60, "scope": "ACCOUNT_PAYEE"}', 1,
 '2025-06-01 10:00:00+00', '2025-06-01 10:00:00+00'),
('RULE-NEW-01', 'First payment to a new payee',   'NEW_PAYEE',       'LOW',    TRUE,
 '{"schemaVersion": 1, "lookbackDays": 90, "minAmount": 500}', 1,
 '2025-06-01 10:00:00+00', '2025-06-01 10:00:00+00'),
('RULE-DAY-01', 'Daily outgoing limit',           'DAILY_LIMIT',     'HIGH',   TRUE,
 '{"schemaVersion": 2, "dailyLimit": 25000, "currency": "EUR"}', 3,
 '2025-06-01 10:00:00+00', '2026-02-18 16:30:00+00'),
('RULE-VEL-02', 'More than 3 card payments / 10 min', 'VELOCITY',    'MEDIUM', FALSE,
 '{"schemaVersion": 1, "maxCount": 3, "windowMinutes": 10, "channel": "APP"}', 2,
 '2025-07-15 10:00:00+00', '2026-01-09 11:00:00+00');

-- ----------------------------------------------------------- rule_history
-- RULE-DAY-01 went 15 000 -> 20 000 -> 25 000. Alerts still point at the version
-- that fired them, which is the whole point of rules.version / alerts.rule_version.
INSERT INTO rule_history (rule_id, version, action, previous_snapshot, new_snapshot, changed_fields, changed_by, changed_at, reason, correlation_id) VALUES
('RULE-DAY-01', 1, 'CREATED', NULL,
 '{"dailyLimit": 15000, "currency": "EUR"}', '["*"]', 'SYSTEM',
 '2025-06-01 10:00:00+00', 'Initial rule set deployment', 'corr-rule-0001'),
('RULE-DAY-01', 2, 'UPDATED',
 '{"dailyLimit": 15000, "currency": "EUR"}', '{"dailyLimit": 20000, "currency": "EUR"}',
 '["config.dailyLimit"]', 'j.moreau',
 '2025-11-03 14:12:00+00', 'Too many false positives on corporate accounts', 'corr-rule-0002'),
('RULE-DAY-01', 3, 'UPDATED',
 '{"dailyLimit": 20000, "currency": "EUR"}', '{"dailyLimit": 25000, "currency": "EUR"}',
 '["config.dailyLimit", "config.schemaVersion"]', 'j.moreau',
 '2026-02-18 16:30:00+00', 'Annual review, aligned with new AML policy', 'corr-rule-0003'),
('RULE-VEL-02', 1, 'CREATED', NULL,
 '{"maxCount": 3, "windowMinutes": 10}', '["*"]', 'SYSTEM',
 '2025-07-15 10:00:00+00', 'Pilot rule for the mobile app channel', 'corr-rule-0004'),
('RULE-VEL-02', 2, 'DEACTIVATED',
 '{"active": true}', '{"active": false}', '["active"]', 'a.kaur',
 '2026-01-09 11:00:00+00', 'Superseded by RULE-VEL-01, noise ratio above 80%', 'corr-rule-0005'),
('RULE-AMT-01', 1, 'CREATED', NULL,
 '{"threshold": 10000, "currency": "EUR"}', '["*"]', 'SYSTEM',
 '2025-06-01 10:00:00+00', 'Initial rule set deployment', 'corr-rule-0006'),
('RULE-VEL-01', 1, 'CREATED', NULL,
 '{"maxCount": 5, "windowMinutes": 60}', '["*"]', 'SYSTEM',
 '2025-06-01 10:00:00+00', 'Initial rule set deployment', 'corr-rule-0007'),
('RULE-NEW-01', 1, 'CREATED', NULL,
 '{"lookbackDays": 90, "minAmount": 500}', '["*"]', 'SYSTEM',
 '2025-06-01 10:00:00+00', 'Initial rule set deployment', 'corr-rule-0008');

-- ------------------------------------------------------------ transactions
-- payload_hash is faked with md5()||md5() so it stays a valid 64-char hex string.

-- ACC-1001 / 2026-03-10: one big payment + a busy day over the daily limit
INSERT INTO transactions (id, account_id, payee_id, amount, currency, type, status,
                          transaction_time, received_at, evaluation_mode, evaluated_at,
                          description, ip_address, device_id, channel, country_code,
                          payment_method, reference_transaction_id, payload_hash) VALUES
('TXN-0001', 'ACC-1001', 'PAY-2005', 12500.0000, 'EUR', 'DEBIT', 'COMPLETED',
 '2026-03-10 08:15:00+00', '2026-03-10 08:15:02+00', 'REAL_TIME', '2026-03-10 08:15:03+00',
 'Consulting invoice 2026-114', '82.64.11.203', 'dev-web-a91', 'WEB', 'FR',
 'BANK_TRANSFER', NULL, md5('TXN-0001') || md5('payload-TXN-0001')),
('TXN-0002', 'ACC-1001', 'PAY-2005', 7800.0000, 'EUR', 'DEBIT', 'COMPLETED',
 '2026-03-10 09:40:00+00', '2026-03-10 09:40:01+00', 'REAL_TIME', '2026-03-10 09:40:02+00',
 'Consulting invoice 2026-115', '82.64.11.203', 'dev-web-a91', 'WEB', 'FR',
 'BANK_TRANSFER', NULL, md5('TXN-0002') || md5('payload-TXN-0002')),
('TXN-0003', 'ACC-1001', 'PAY-2003', 6200.0000, 'EUR', 'DEBIT', 'COMPLETED',
 '2026-03-10 11:05:00+00', '2026-03-10 11:05:01+00', 'REAL_TIME', '2026-03-10 11:05:04+00',
 'Deposit', '82.64.11.203', 'dev-app-77c', 'APP', 'FR',
 'BANK_TRANSFER', NULL, md5('TXN-0003') || md5('payload-TXN-0003')),
('TXN-0004', 'ACC-1001', 'PAY-2003', 950.0000, 'EUR', 'DEBIT', 'COMPLETED',
 '2026-03-11 07:20:00+00', '2026-03-11 07:20:01+00', 'REAL_TIME', '2026-03-11 07:20:02+00',
 'Monthly rent', '82.64.11.203', 'dev-app-77c', 'APP', 'FR',
 'BANK_TRANSFER', NULL, md5('TXN-0004') || md5('payload-TXN-0004')),
('TXN-0005', 'ACC-1001', 'PAY-2001', 3100.0000, 'EUR', 'DEBIT', 'PENDING',
 '2026-03-16 12:00:00+00', '2026-03-16 12:00:01+00', NULL, NULL,
 'Solar panel deposit', '82.64.11.203', 'dev-web-a91', 'WEB', 'FR',
 'BANK_TRANSFER', NULL, md5('TXN-0005') || md5('payload-TXN-0005'));

-- ACC-1002 / 2026-03-12: six card payments to the same payee inside one hour
INSERT INTO transactions (id, account_id, payee_id, amount, currency, type, status,
                          transaction_time, received_at, evaluation_mode, evaluated_at,
                          description, ip_address, device_id, channel, country_code,
                          payment_method, reference_transaction_id, payload_hash) VALUES
('TXN-0010', 'ACC-1002', 'PAY-2006', 420.0000, 'GBP', 'DEBIT', 'COMPLETED',
 '2026-03-12 14:02:00+00', '2026-03-12 14:02:01+00', 'REAL_TIME', '2026-03-12 14:02:02+00',
 'Fabric order #1', '51.11.204.9', 'dev-api-int', 'API', 'GB', 'CARD', NULL,
 md5('TXN-0010') || md5('payload-TXN-0010')),
('TXN-0011', 'ACC-1002', 'PAY-2006', 420.0000, 'GBP', 'DEBIT', 'COMPLETED',
 '2026-03-12 14:11:00+00', '2026-03-12 14:11:01+00', 'REAL_TIME', '2026-03-12 14:11:02+00',
 'Fabric order #2', '51.11.204.9', 'dev-api-int', 'API', 'GB', 'CARD', NULL,
 md5('TXN-0011') || md5('payload-TXN-0011')),
('TXN-0012', 'ACC-1002', 'PAY-2006', 420.0000, 'GBP', 'DEBIT', 'COMPLETED',
 '2026-03-12 14:23:00+00', '2026-03-12 14:23:01+00', 'REAL_TIME', '2026-03-12 14:23:02+00',
 'Fabric order #3', '51.11.204.9', 'dev-api-int', 'API', 'GB', 'CARD', NULL,
 md5('TXN-0012') || md5('payload-TXN-0012')),
('TXN-0013', 'ACC-1002', 'PAY-2006', 420.0000, 'GBP', 'DEBIT', 'COMPLETED',
 '2026-03-12 14:35:00+00', '2026-03-12 14:35:01+00', 'REAL_TIME', '2026-03-12 14:35:02+00',
 'Fabric order #4', '51.11.204.9', 'dev-api-int', 'API', 'GB', 'CARD', NULL,
 md5('TXN-0013') || md5('payload-TXN-0013')),
('TXN-0014', 'ACC-1002', 'PAY-2006', 420.0000, 'GBP', 'DEBIT', 'COMPLETED',
 '2026-03-12 14:44:00+00', '2026-03-12 14:44:01+00', 'REAL_TIME', '2026-03-12 14:44:03+00',
 'Fabric order #5', '51.11.204.9', 'dev-api-int', 'API', 'GB', 'CARD', NULL,
 md5('TXN-0014') || md5('payload-TXN-0014')),
('TXN-0015', 'ACC-1002', 'PAY-2006', 420.0000, 'GBP', 'DEBIT', 'COMPLETED',
 '2026-03-12 14:51:00+00', '2026-03-12 14:51:01+00', 'REAL_TIME', '2026-03-12 14:51:02+00',
 'Fabric order #6', '51.11.204.9', 'dev-api-int', 'API', 'GB', 'CARD', NULL,
 md5('TXN-0015') || md5('payload-TXN-0015')),
('TXN-0016', 'ACC-1002', 'PAY-2001', 1800.0000, 'GBP', 'DEBIT', 'COMPLETED',
 '2026-03-13 09:30:00+00', '2026-03-13 09:30:01+00', 'REAL_TIME', '2026-03-13 09:30:02+00',
 'Warehouse electricity', '51.11.204.9', 'dev-web-b02', 'WEB', 'GB', 'BANK_TRANSFER', NULL,
 md5('TXN-0016') || md5('payload-TXN-0016'));

-- ACC-1003: quiet account, one new payee, then a refund
INSERT INTO transactions (id, account_id, payee_id, amount, currency, type, status,
                          transaction_time, received_at, evaluation_mode, evaluated_at,
                          description, ip_address, device_id, channel, country_code,
                          payment_method, reference_transaction_id, payload_hash) VALUES
('TXN-0020', 'ACC-1003', 'PAY-2004', 2500.0000, 'THB', 'DEBIT', 'COMPLETED',
 '2026-03-09 03:30:00+00', '2026-03-09 03:30:01+00', 'REAL_TIME', '2026-03-09 03:30:02+00',
 'Electricity bill', '171.6.40.88', 'dev-app-tha', 'APP', 'TH', 'BANK_TRANSFER', NULL,
 md5('TXN-0020') || md5('payload-TXN-0020')),
('TXN-0021', 'ACC-1003', 'PAY-2008', 1200.0000, 'USD', 'DEBIT', 'COMPLETED',
 '2026-03-13 06:12:00+00', '2026-03-13 06:12:01+00', 'REAL_TIME', '2026-03-13 06:12:03+00',
 'Annual hosting plan', '171.6.40.88', 'dev-app-tha', 'APP', 'TH', 'CARD', NULL,
 md5('TXN-0021') || md5('payload-TXN-0021')),
('TXN-0022', 'ACC-1003', 'PAY-2008', 1200.0000, 'USD', 'REFUND', 'COMPLETED',
 '2026-03-14 10:45:00+00', '2026-03-14 10:45:01+00', 'REAL_TIME', '2026-03-14 10:45:02+00',
 'Hosting plan cancelled within 24h', '171.6.40.88', 'dev-app-tha', 'APP', 'TH', 'CARD', 'TXN-0021',
 md5('TXN-0022') || md5('payload-TXN-0022')),
('TXN-0023', 'ACC-1003', 'PAY-2004', 2610.0000, 'THB', 'DEBIT', 'COMPLETED',
 '2026-04-09 03:28:00+00', '2026-04-11 08:00:00+00', 'LATE_ARRIVAL', '2026-04-11 08:00:05+00',
 'Electricity bill (batch replay)', '171.6.40.88', 'dev-app-tha', 'APP', 'TH', 'BANK_TRANSFER', NULL,
 md5('TXN-0023') || md5('payload-TXN-0023'));

-- ACC-1004: blocked account, failed and cancelled traffic
INSERT INTO transactions (id, account_id, payee_id, amount, currency, type, status,
                          transaction_time, received_at, evaluation_mode, evaluated_at,
                          description, ip_address, device_id, channel, country_code,
                          payment_method, reference_transaction_id, payload_hash) VALUES
('TXN-0030', 'ACC-1004', 'PAY-2007', 4300.0000, 'EUR', 'DEBIT', 'FAILED',
 '2026-03-08 10:00:00+00', '2026-03-08 10:00:01+00', 'REAL_TIME', '2026-03-08 10:00:02+00',
 'Supplier payment - insufficient funds', '95.120.7.14', 'dev-branch-mad', 'BRANCH', 'ES',
 'BANK_TRANSFER', NULL, md5('TXN-0030') || md5('payload-TXN-0030')),
('TXN-0031', 'ACC-1004', 'PAY-2002', 15000.0000, 'EUR', 'DEBIT', 'CANCELLED',
 '2026-03-15 18:00:00+00', '2026-03-15 18:00:01+00', 'REAL_TIME', '2026-03-15 18:00:02+00',
 'Currency exchange', '185.220.101.44', 'dev-web-unk', 'WEB', 'RO',
 'BANK_TRANSFER', NULL, md5('TXN-0031') || md5('payload-TXN-0031'));

-- ACC-1005: the baseline. Small, regular, one new payee that turned out fine.
INSERT INTO transactions (id, account_id, payee_id, amount, currency, type, status,
                          transaction_time, received_at, evaluation_mode, evaluated_at,
                          description, ip_address, device_id, channel, country_code,
                          payment_method, reference_transaction_id, payload_hash) VALUES
('TXN-0040', 'ACC-1005', 'PAY-2001', 240.0000, 'SGD', 'DEBIT', 'COMPLETED',
 '2026-03-05 02:10:00+00', '2026-03-05 02:10:01+00', 'REAL_TIME', '2026-03-05 02:10:02+00',
 'Utilities', '116.88.3.201', 'dev-app-sg1', 'APP', 'SG', 'WALLET', NULL,
 md5('TXN-0040') || md5('payload-TXN-0040')),
('TXN-0041', 'ACC-1005', 'PAY-2007', 900.0000, 'SGD', 'DEBIT', 'COMPLETED',
 '2026-03-11 05:45:00+00', '2026-03-11 05:45:01+00', 'REAL_TIME', '2026-03-11 05:45:02+00',
 'Freelance designer invoice', '116.88.3.201', 'dev-app-sg1', 'APP', 'SG', 'BANK_TRANSFER', NULL,
 md5('TXN-0041') || md5('payload-TXN-0041')),
('TXN-0042', 'ACC-1005', 'PAY-2001', 260.0000, 'SGD', 'DEBIT', 'COMPLETED',
 '2026-04-05 02:12:00+00', '2026-04-05 02:12:01+00', 'REAL_TIME', '2026-04-05 02:12:02+00',
 'Utilities', '116.88.3.201', 'dev-app-sg1', 'APP', 'SG', 'WALLET', NULL,
 md5('TXN-0042') || md5('payload-TXN-0042'));

-- ------------------------------------------------------------------ alerts
INSERT INTO alerts (id, rule_id, rule_version, account_id, primary_payee_id, first_trigger_transaction_id,
                    deduplication_key, status, severity, reason_text, rule_snapshot, trigger_context,
                    episode_start, last_triggered_at, transaction_count, cumulative_amount,
                    resolution_code, resolution_notes, version,
                    created_at, updated_at, acknowledged_at, investigation_started_at, closed_at, dismissed_at) VALUES

-- 1. Amount threshold, still OPEN
('ALR-9001', 'RULE-AMT-01', 1, 'ACC-1001', 'PAY-2005', 'TXN-0001',
 'AMOUNT_THRESHOLD|RULE-AMT-01|ACC-1001|TXN-0001', 'OPEN', 'HIGH',
 'Payment of 12 500.00 EUR exceeds the 10 000.00 EUR single-payment threshold.',
 '{"threshold": 10000, "currency": "EUR", "schemaVersion": 1}',
 '{"amount": 12500.0, "currency": "EUR", "payeeCountry": "KY", "channel": "WEB"}',
 '2026-03-10 08:15:00+00', '2026-03-10 08:15:00+00', 1, 12500.0000,
 NULL, NULL, 1,
 '2026-03-10 08:15:03+00', '2026-03-10 08:15:03+00', NULL, NULL, NULL, NULL),

-- 2. Daily limit on the same account, same day, ACKNOWLEDGED
('ALR-9002', 'RULE-DAY-01', 3, 'ACC-1001', NULL, 'TXN-0003',
 'DAILY_LIMIT|RULE-DAY-01|ACC-1001|2026-03-10', 'ACKNOWLEDGED', 'HIGH',
 'Cumulative outgoing amount of 26 500.00 EUR exceeds the 25 000.00 EUR daily limit.',
 '{"dailyLimit": 25000, "currency": "EUR", "schemaVersion": 2}',
 '{"day": "2026-03-10", "cumulative": 26500.0, "transactionCount": 3}',
 '2026-03-10 08:15:00+00', '2026-03-10 11:05:00+00', 3, 26500.0000,
 NULL, NULL, 2,
 '2026-03-10 11:05:04+00', '2026-03-10 13:20:00+00', '2026-03-10 13:20:00+00', NULL, NULL, NULL),

-- 3. Velocity episode: 6 transactions, 1 alert
('ALR-9003', 'RULE-VEL-01', 1, 'ACC-1002', 'PAY-2006', 'TXN-0014',
 'VELOCITY|RULE-VEL-01|ACC-1002|PAY-2006|2026-03-12T14', 'INVESTIGATING', 'MEDIUM',
 '5 payments to the same payee within 60 minutes (limit: 5).',
 '{"maxCount": 5, "windowMinutes": 60, "scope": "ACCOUNT_PAYEE", "schemaVersion": 1}',
 '{"windowStart": "2026-03-12T14:02:00Z", "windowEnd": "2026-03-12T14:51:00Z", "count": 6}',
 '2026-03-12 14:02:00+00', '2026-03-12 14:51:00+00', 6, 2520.0000,
 NULL, NULL, 3,
 '2026-03-12 14:44:03+00', '2026-03-12 15:10:00+00', '2026-03-12 14:58:00+00', '2026-03-12 15:10:00+00', NULL, NULL),

-- 4. New payee, DISMISSED
('ALR-9004', 'RULE-NEW-01', 1, 'ACC-1003', 'PAY-2008', 'TXN-0021',
 'NEW_PAYEE|RULE-NEW-01|ACC-1003|PAY-2008', 'DISMISSED', 'LOW',
 'First payment to payee CloudHost Inc within the 90-day lookback window.',
 '{"lookbackDays": 90, "minAmount": 500, "schemaVersion": 1}',
 '{"amount": 1200.0, "currency": "USD", "priorPaymentCount": 0}',
 '2026-03-13 06:12:00+00', '2026-03-13 06:12:00+00', 1, 1200.0000,
 NULL, 'Known SaaS provider, customer confirmed the subscription by phone.', 2,
 '2026-03-13 06:12:03+00', '2026-03-13 08:40:00+00', NULL, NULL, NULL, '2026-03-13 08:40:00+00'),

-- 5. Amount threshold on a blocked account, CLOSED as suspicious
('ALR-9005', 'RULE-AMT-01', 1, 'ACC-1004', 'PAY-2002', 'TXN-0031',
 'AMOUNT_THRESHOLD|RULE-AMT-01|ACC-1004|TXN-0031', 'CLOSED', 'HIGH',
 'Payment of 15 000.00 EUR to a blocked payee exceeds the 10 000.00 EUR threshold.',
 '{"threshold": 10000, "currency": "EUR", "schemaVersion": 1}',
 '{"amount": 15000.0, "currency": "EUR", "payeeStatus": "BLOCKED", "ipCountry": "RO", "accountCountry": "ES"}',
 '2026-03-15 18:00:00+00', '2026-03-15 18:00:00+00', 1, 15000.0000,
 'SUSPICIOUS_ACTIVITY', 'Transaction cancelled, account blocked, escalated to the AML team.', 4,
 '2026-03-15 18:00:02+00', '2026-03-16 09:15:00+00', '2026-03-15 18:30:00+00', '2026-03-15 19:00:00+00', '2026-03-16 09:15:00+00', NULL),

-- 6. New payee, CLOSED as a false positive
('ALR-9006', 'RULE-NEW-01', 1, 'ACC-1005', 'PAY-2007', 'TXN-0041',
 'NEW_PAYEE|RULE-NEW-01|ACC-1005|PAY-2007', 'CLOSED', 'LOW',
 'First payment to payee Emma Rivera within the 90-day lookback window.',
 '{"lookbackDays": 90, "minAmount": 500, "schemaVersion": 1}',
 '{"amount": 900.0, "currency": "SGD", "priorPaymentCount": 0}',
 '2026-03-11 05:45:00+00', '2026-03-11 05:45:00+00', 1, 900.0000,
 'FALSE_POSITIVE', 'Recurring freelance supplier, rule threshold too low for this segment.', 3,
 '2026-03-11 05:45:02+00', '2026-03-12 10:00:00+00', '2026-03-11 09:00:00+00', NULL, '2026-03-12 10:00:00+00', NULL);

-- ------------------------------------------------------- alert_transactions
INSERT INTO alert_transactions (alert_id, transaction_id, linked_at, link_reason) VALUES
('ALR-9001', 'TXN-0001', '2026-03-10 08:15:03+00', 'FIRST_TRIGGER'),

('ALR-9002', 'TXN-0003', '2026-03-10 11:05:04+00', 'FIRST_TRIGGER'),
('ALR-9002', 'TXN-0001', '2026-03-10 11:05:04+00', 'WINDOW_CONTEXT'),
('ALR-9002', 'TXN-0002', '2026-03-10 11:05:04+00', 'WINDOW_CONTEXT'),

('ALR-9003', 'TXN-0014', '2026-03-12 14:44:03+00', 'FIRST_TRIGGER'),
('ALR-9003', 'TXN-0010', '2026-03-12 14:44:03+00', 'WINDOW_CONTEXT'),
('ALR-9003', 'TXN-0011', '2026-03-12 14:44:03+00', 'WINDOW_CONTEXT'),
('ALR-9003', 'TXN-0012', '2026-03-12 14:44:03+00', 'WINDOW_CONTEXT'),
('ALR-9003', 'TXN-0013', '2026-03-12 14:44:03+00', 'WINDOW_CONTEXT'),
('ALR-9003', 'TXN-0015', '2026-03-12 14:51:02+00', 'SUBSEQUENT_TRIGGER'),

('ALR-9004', 'TXN-0021', '2026-03-13 06:12:03+00', 'FIRST_TRIGGER'),
('ALR-9005', 'TXN-0031', '2026-03-15 18:00:02+00', 'FIRST_TRIGGER'),
('ALR-9006', 'TXN-0041', '2026-03-11 05:45:02+00', 'FIRST_TRIGGER');

-- ----------------------------------------------------------- alert_history
INSERT INTO alert_history (alert_id, event_type, from_status, to_status, note, previous_values, new_values, changed_at, changed_by, source, correlation_id) VALUES
('ALR-9001', 'CREATED', NULL, 'OPEN', 'Alert raised by RULE-AMT-01', NULL,
 '{"status": "OPEN", "severity": "HIGH"}', '2026-03-10 08:15:03+00', 'SYSTEM', 'SYSTEM', 'corr-evt-0001'),

('ALR-9002', 'CREATED', NULL, 'OPEN', 'Alert raised by RULE-DAY-01', NULL,
 '{"status": "OPEN", "cumulativeAmount": 26500.0}', '2026-03-10 11:05:04+00', 'SYSTEM', 'SYSTEM', 'corr-evt-0002'),
('ALR-9002', 'STATUS_CHANGED', 'OPEN', 'ACKNOWLEDGED', 'Picked up by the day shift',
 '{"status": "OPEN"}', '{"status": "ACKNOWLEDGED"}', '2026-03-10 13:20:00+00', 'l.bernard', 'OPERATOR', 'corr-evt-0003'),

('ALR-9003', 'CREATED', NULL, 'OPEN', 'Velocity threshold reached on the 5th payment', NULL,
 '{"status": "OPEN", "transactionCount": 5}', '2026-03-12 14:44:03+00', 'SYSTEM', 'SYSTEM', 'corr-evt-0004'),
('ALR-9003', 'TRANSACTION_LINKED', NULL, NULL, 'TXN-0015 attached to the running episode',
 '{"transactionCount": 5}', '{"transactionCount": 6, "transactionId": "TXN-0015"}',
 '2026-03-12 14:51:02+00', 'SYSTEM', 'SYSTEM', 'corr-evt-0005'),
('ALR-9003', 'TRIGGER_METRICS_UPDATED', NULL, NULL, 'Cumulative amount recomputed',
 '{"cumulativeAmount": 2100.0}', '{"cumulativeAmount": 2520.0}',
 '2026-03-12 14:51:02+00', 'SYSTEM', 'SYSTEM', 'corr-evt-0006'),
('ALR-9003', 'STATUS_CHANGED', 'OPEN', 'ACKNOWLEDGED', NULL,
 '{"status": "OPEN"}', '{"status": "ACKNOWLEDGED"}', '2026-03-12 14:58:00+00', 'l.bernard', 'OPERATOR', 'corr-evt-0007'),
('ALR-9003', 'STATUS_CHANGED', 'ACKNOWLEDGED', 'INVESTIGATING', 'Contacting the corporate customer',
 '{"status": "ACKNOWLEDGED"}', '{"status": "INVESTIGATING"}', '2026-03-12 15:10:00+00', 'l.bernard', 'OPERATOR', 'corr-evt-0008'),

('ALR-9004', 'CREATED', NULL, 'OPEN', 'Alert raised by RULE-NEW-01', NULL,
 '{"status": "OPEN"}', '2026-03-13 06:12:03+00', 'SYSTEM', 'SYSTEM', 'corr-evt-0009'),
('ALR-9004', 'STATUS_CHANGED', 'OPEN', 'DISMISSED', 'Customer confirmed the payment',
 '{"status": "OPEN"}', '{"status": "DISMISSED"}', '2026-03-13 08:40:00+00', 'p.nguyen', 'OPERATOR', 'corr-evt-0010'),

('ALR-9005', 'CREATED', NULL, 'OPEN', 'Alert raised by RULE-AMT-01', NULL,
 '{"status": "OPEN"}', '2026-03-15 18:00:02+00', 'SYSTEM', 'SYSTEM', 'corr-evt-0011'),
('ALR-9005', 'STATUS_CHANGED', 'OPEN', 'ACKNOWLEDGED', NULL,
 '{"status": "OPEN"}', '{"status": "ACKNOWLEDGED"}', '2026-03-15 18:30:00+00', 'a.kaur', 'OPERATOR', 'corr-evt-0012'),
('ALR-9005', 'STATUS_CHANGED', 'ACKNOWLEDGED', 'INVESTIGATING', 'Payee on the internal blocklist',
 '{"status": "ACKNOWLEDGED"}', '{"status": "INVESTIGATING"}', '2026-03-15 19:00:00+00', 'a.kaur', 'OPERATOR', 'corr-evt-0013'),
('ALR-9005', 'RESOLUTION_UPDATED', NULL, NULL, 'Resolution code recorded', NULL,
 '{"resolutionCode": "SUSPICIOUS_ACTIVITY"}', '2026-03-16 09:14:00+00', 'a.kaur', 'OPERATOR', 'corr-evt-0014'),
('ALR-9005', 'STATUS_CHANGED', 'INVESTIGATING', 'CLOSED', 'Escalated to AML, account blocked',
 '{"status": "INVESTIGATING"}', '{"status": "CLOSED"}', '2026-03-16 09:15:00+00', 'a.kaur', 'OPERATOR', 'corr-evt-0015'),

('ALR-9006', 'CREATED', NULL, 'OPEN', 'Alert raised by RULE-NEW-01', NULL,
 '{"status": "OPEN"}', '2026-03-11 05:45:02+00', 'SYSTEM', 'SYSTEM', 'corr-evt-0016'),
('ALR-9006', 'STATUS_CHANGED', 'OPEN', 'ACKNOWLEDGED', NULL,
 '{"status": "OPEN"}', '{"status": "ACKNOWLEDGED"}', '2026-03-11 09:00:00+00', 'p.nguyen', 'OPERATOR', 'corr-evt-0017'),
('ALR-9006', 'STATUS_CHANGED', 'ACKNOWLEDGED', 'CLOSED', 'Closed as false positive',
 '{"status": "ACKNOWLEDGED"}', '{"status": "CLOSED", "resolutionCode": "FALSE_POSITIVE"}',
 '2026-03-12 10:00:00+00', 'p.nguyen', 'OPERATOR', 'corr-evt-0018');

-- ----------------------------------------------------- idempotency_records
INSERT INTO idempotency_records (operation_scope, idempotency_key, request_hash, status, http_status, response_body, resource_id, created_at, expires_at) VALUES
('POST /transactions', 'key-ingest-0001', md5('req-1') || md5('req-1b'), 'SUCCEEDED', 201,
 '{"id": "TXN-0001"}', 'TXN-0001', '2026-03-10 08:15:02+00', '2026-03-11 08:15:02+00'),
('POST /transactions', 'key-ingest-0002', md5('req-2') || md5('req-2b'), 'SUCCEEDED', 200,
 '{"id": "TXN-0001", "duplicate": true}', 'TXN-0001', '2026-03-10 08:15:09+00', '2026-03-11 08:15:09+00'),
('PATCH /alerts/ALR-9002', 'key-ack-0007', md5('req-3') || md5('req-3b'), 'SUCCEEDED', 200,
 '{"id": "ALR-9002", "status": "ACKNOWLEDGED"}', 'ALR-9002', '2026-03-10 13:20:00+00', '2026-03-11 13:20:00+00'),
('POST /transactions', 'key-ingest-0099', md5('req-4') || md5('req-4b'), 'FAILED', 422,
 '{"error": "UNKNOWN_PAYEE"}', NULL, '2026-03-16 12:04:00+00', '2026-03-17 12:04:00+00');

COMMIT;
